DESC EMP_COPY;
DROP TABLE EMP_COPY;

DESC DEPT_COPY;
DROP TABLE DEPT_COPY;

CREATE TABLE EMP_COPY
    AS SELECT * FROM EMP;
    
CREATE TABLE DEPT_COPY
    AS SELECT * FROM DEPT;

-- 제약조건 확인하기    
SELECT TABLE_NAME, CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP_COPY', 'DEPT_COPY');

-- PRIMARY KEY 제약 조건 추가하기
ALTER TABLE EMP_COPY
ADD CONSTRAINT EMP_COPY_EMPNO_PK PRIMARY KEY(EMPNO);

ALTER TABLE DEPT_COPY
ADD CONSTRAINT DEPT_COPY_DEPTNO_PK PRIMARY KEY(DEPTNO);

-- FOREIGN KEY 제약 조건 추가하기
ALTER TABLE EMP_COPY
ADD CONSTRAINT EMP_COPY_DEPTNO_FK 
FOREIGN KEY(DEPTNO) REFERENCES DEPT_COPY(DEPTNO);

-- 제약조건 확인하기    
SELECT TABLE_NAME, CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP_COPY', 'DEPT_COPY');

-- MODIFY NOT NULL로 NULL값 허용하지 않기
ALTER TABLE EMP_COPY
MODIFY ENAME CONSTRAINT EMP_COPY_ENAME_NN NOT NULL;

-- 제약조건 확인하기    
SELECT TABLE_NAME, CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP_COPY', 'DEPT_COPY');

-- 제약조건 제거하기
ALTER TABLE DEPT_COPY
DROP PRIMARY KEY;

-- CASCADE 옵션으로 종속 제약 조건까지 모두 제거하기
ALTER TABLE DEPT_COPY
DROP PRIMARY KEY CASCADE;

-- 제약조건 확인하기    
SELECT TABLE_NAME, CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP_COPY', 'DEPT_COPY');

-- NOT NULL 제약조건 제거하기
ALTER TABLE EMP_COPY
DROP CONSTRAINT EMP_COPY_ENAME_NN;

-- 제약조건 확인하기    
SELECT TABLE_NAME, CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP_COPY', 'DEPT_COPY');

