--125p Q1.

SELECT *
FROM EMP
WHERE ENAME LIKE '%S';

--Q2.

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE JOB = 'SALESMAN';

--03.
-- 집합 연산자를 사용하지 않은 방식
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30) AND SAL>2000;

-- 집합 연산자를 사용한 방식
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20 AND SAL>2000

UNION

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30 AND SAL>2000;

--Q4.

 SELECT *
 FROM EMP 
 WHERE SAL NOT BETWEEN 2000 AND 3000;

--Q5. 

SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%' 
  AND DEPTNO = 30
  AND SAL NOT BETWEEN 1000 AND 2000;


--Q6

 SELECT *
 FROM EMP
 WHERE COMM IS NULL
 AND MGR IS NOT NULL
 AND JOB IN('MANAGER','CLERK')
 AND ENAME NOT LIKE '_L%';